name: benchmark

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: sudo apt-get install -y csvkit
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true
      - uses: actions/checkout@v4
      - name: go mod tidy
        run: |
          mkdir bench
          cd bench
          awk '{if($0 ~ "// go test -v"){a=1;b=1};if($0 ~ "```" && b=1){b=0};if (a&&b) {print}}' ../README.md | tee bench_test.go
          go mod tidy
          go mod edit -replace github.com/phuslu/lru=../
      - name: Tests
        run: |
          go test -v -bench=. -race -count=1 -coverprofile=coverage.txt
      - name: Benchmark
        working-directory: ./bench
        run: |
          go test -v -cpu=8 -run=none -bench=. -benchtime=5s -benchmem bench_test.go
          env zipf=1 go test -v -cpu=8 -run=none -bench=. -benchtime=5s -benchmem bench_test.go
      - name: Memory Usage
        working-directory: ./bench
        run: |
          awk '{if($0 ~ "// memusage.go"){a=1;b=1};if($0 ~ "```" && b=1){b=0};if (a&&b) {print}}' ../README.md > memusage.go
          echo -e 'MemStats\tAlloc\tTotalAlloc\tSys' > memusage.txt
          go run memusage.go phuslu     >> memusage.txt
          go run memusage.go lxzan      >> memusage.txt
          go run memusage.go freelru    >> memusage.txt
          go run memusage.go ecache     >> memusage.txt
          go run memusage.go ristretto  >> memusage.txt
          go run memusage.go otter      >> memusage.txt
          go run memusage.go theine     >> memusage.txt
          go run memusage.go cloudflare >> memusage.txt
          cat memusage.txt | csvlook
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
