name: benchmark

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: sudo apt update -y && sudo apt-get install -y csvkit datamash
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          check-latest: true
      - uses: actions/checkout@v4
      - name: go mod tidy
        run: |
          mkdir bench
          cd bench
          awk '{if($0 ~ "// env writeratio="){a=1;b=1};if($0 ~ "```" && b=1){b=0};if (a&&b) {print}}' ../README.md | tee bench_test.go
          go mod init bench
          go mod tidy
          go mod edit -replace github.com/phuslu/lru=../
          cat go.mod
      - name: Tests
        run: |
          go test -v -bench=. -race -count=1 -coverprofile=coverage.txt
      - name: Throughput benchmarks
        working-directory: ./bench
        run: |
          env writeratio=0.1 zipf=false go test -v -cpu=8 -run=none -bench=. -benchtime=5s -benchmem bench_test.go
          env writeratio=0.01 zipf=true go test -v -cpu=8 -run=none -bench=. -benchtime=5s -benchmem bench_test.go
      - name: Memory Usage
        working-directory: ./bench
        run: |
          awk '{if($0 ~ "// memusage.go"){a=1;b=1};if($0 ~ "```" && b=1){b=0};if (a&&b) {print}}' ../README.md > memusage.go
          echo -e 'MemStats\tCacheSize\tAlloc\tTotalAlloc\tSys' > memusage.txt
          for name in phuslu lxzan ristretto freelru ecache otter theine cloudflare ccache hashicorp; do
            for cachesize in 100000 200000 400000 1000000 2000000 4000000; do
              go run memusage.go $name $cachesize >> memusage.txt
            done
          done
          cat memusage.txt
          cat memusage.txt | datamash --header-in crosstab 1,2 unique 3 | tee >(head -1) | tail -n +2 | sort -k12 -n | datamash transpose | tee >(head -1) | tail -n +2 | sort -n | datamash transpose | csvlook
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
